
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi1.testphone;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS_MINUS = 48;
  public static final int LEFT = 67;
  public static final int TIMES = 43;
  public static final int MINUS_EQUALS = 50;
  public static final int RIGHT = 66;
  public static final int TOP = 65;
  public static final int MENOR_EQUALS = 58;
  public static final int MAYOR = 55;
  public static final int NAME = 27;
  public static final int X_AXIS_L = 21;
  public static final int CORCHETE_R = 37;
  public static final int KEYWORDS = 9;
  public static final int HEADER = 10;
  public static final int INTEGER = 68;
  public static final int CORCHETE_L = 36;
  public static final int DIV_EQUALS = 52;
  public static final int PLUS_EQUALS = 49;
  public static final int BACKGROUND = 12;
  public static final int LLAVE_R = 34;
  public static final int DIFFERENT = 54;
  public static final int TWO_DOTS = 35;
  public static final int LLAVE_L = 33;
  public static final int FLOAT = 69;
  public static final int PLUS_PLUS = 47;
  public static final int DOT_COMA = 39;
  public static final int CATEGORY = 17;
  public static final int MAYOR_EQUALS = 56;
  public static final int LEGEND_POS = 24;
  public static final int ASIGNATOR = 42;
  public static final int LINE_STYLE = 29;
  public static final int COMA = 38;
  public static final int CHART = 20;
  public static final int PLUS = 44;
  public static final int WHILE = 5;
  public static final int PARENTESIS_R = 41;
  public static final int DO = 6;
  public static final int VARIABLE = 61;
  public static final int FOR = 4;
  public static final int X_DATA = 25;
  public static final int DIV = 45;
  public static final int PARENTESIS_L = 40;
  public static final int ICON = 30;
  public static final int ELSE = 3;
  public static final int MENOR = 57;
  public static final int FALSE_B = 71;
  public static final int Y_AXIS_L = 22;
  public static final int LINK = 31;
  public static final int EOF = 0;
  public static final int TIMES_EQUALS = 51;
  public static final int LABEL = 23;
  public static final int MINUS = 46;
  public static final int Y_DATA = 26;
  public static final int TITLE = 7;
  public static final int error = 1;
  public static final int DATA = 16;
  public static final int DASHED_LINE = 62;
  public static final int SOLID_LINE = 63;
  public static final int IF = 2;
  public static final int COLOR = 19;
  public static final int BOTTOM = 64;
  public static final int HEX_COLOR = 59;
  public static final int DESCRIPTION = 8;
  public static final int FONT_FAMILY = 13;
  public static final int FONT_SIZE = 14;
  public static final int FOOTER = 11;
  public static final int STRING = 60;
  public static final int SIZE = 32;
  public static final int TRUE_B = 70;
  public static final int COPYRIGHT = 15;
  public static final int VALUE = 18;
  public static final int POINTS = 28;
  public static final int EQUALS = 53;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "TITLE",
  "DESCRIPTION",
  "KEYWORDS",
  "HEADER",
  "FOOTER",
  "BACKGROUND",
  "FONT_FAMILY",
  "FONT_SIZE",
  "COPYRIGHT",
  "DATA",
  "CATEGORY",
  "VALUE",
  "COLOR",
  "CHART",
  "X_AXIS_L",
  "Y_AXIS_L",
  "LABEL",
  "LEGEND_POS",
  "X_DATA",
  "Y_DATA",
  "NAME",
  "POINTS",
  "LINE_STYLE",
  "ICON",
  "LINK",
  "SIZE",
  "LLAVE_L",
  "LLAVE_R",
  "TWO_DOTS",
  "CORCHETE_L",
  "CORCHETE_R",
  "COMA",
  "DOT_COMA",
  "PARENTESIS_L",
  "PARENTESIS_R",
  "ASIGNATOR",
  "TIMES",
  "PLUS",
  "DIV",
  "MINUS",
  "PLUS_PLUS",
  "MINUS_MINUS",
  "PLUS_EQUALS",
  "MINUS_EQUALS",
  "TIMES_EQUALS",
  "DIV_EQUALS",
  "EQUALS",
  "DIFFERENT",
  "MAYOR",
  "MAYOR_EQUALS",
  "MENOR",
  "MENOR_EQUALS",
  "HEX_COLOR",
  "STRING",
  "VARIABLE",
  "DASHED_LINE",
  "SOLID_LINE",
  "BOTTOM",
  "TOP",
  "RIGHT",
  "LEFT",
  "INTEGER",
  "FLOAT",
  "TRUE_B",
  "FALSE_B"
  };
}

